openapi: 3.0.1
info:
  title: Описание API Статистики
  version: '2.18'
security:
  - HeaderApiKey: [ ]
x-tagGroups:
  - name: Статистика
    tags:
      - Статистика
  - name: Отчёты
    tags:
      - Отчёты
  - name: Отложенная генерация
    tags:
      - Получение отчётов
tags:
  - name: Статистика
    description: 'Методы статистики <br><b>Лимит по запросам:</b> один запрос одного
    метода в минуту. <br><br> <a href="../../excel_save/ru/index.html">Инструкция:
    Сохранение статистики в Excel</a>

    '
  - name: Отчёты
    description: 'В данном разде представлены описания полей отчётов. <br>Процесс получения  отчётов
    описан в разделе документации <b>Отложенная генерация</b>.

    '
  - name: Получение отчётов
    description: "В данном разделе описан процесс получения отчётов способом отложенной\
    \ генерации.<br>  <br> `Для авторизации используйте токен с типом Статистика,\
    \ без флага \"Только на чтение\".`<br>  <br> Для каждого метода допускается не\
    \ более 1 запроса в минуту.   <br>  `Важно!`На данный момент доступна генерация\
    \ только отчёта о платном хранении.        <br> <br>  Порядок получения отчёта:\
    \ <ol>\n  <li> Для начала необходимо создать задание на генерацию отчёта. <br>Отправьте\
    \ запрос с необходимым типом отчёта на <b>POST /api/v1/delayed-gen/tasks/create</b>\n\
    \      <br>\n      В ответе, в поле <b>taskId</b> вернётся номер задания.\n  </li>\n\
    \  <li>\n    Теперь необходимо дождаться выполнения задния на генерацию отчёта.\
    \ \n    <br> С помощью метода <b>GET /api/v1/delayed-gen/tasks</b> Вы можете отслеживать\
    \ статус задания. \n    <br>\n    Когда задание получит статус <code>done</code>,\
    \ можно переходить к последнему пункту.\n  </li>\n  <li>\n    Получите отчет с\
    \ помощью метода <b>GET /api/v1/delayed-gen/tasks/download</b>\n    <br> Описание\
    \ полей находится в разделе документации Отчёты.\n    <br> Сгенерированный отчёт\
    \ хранится 2 часа, после чего автоматически удаляется.\n  </li>\n</ol>\n"
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
  responses:
    200SuccessDownloadedFiles:
      description: Успешно
      content:
        application/json:
          schema:
            oneOf:
              - $ref: '#/components/schemas/ResponsePaidStorage'
    400BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    429TooManyRequests:
      description: Too many requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    500InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    404EntityNotFound:
      description: Entity not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: string
    DownloadRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          description: ID задания
    responseErrorStatistics:
      type: object
      properties:
        errors:
          type: array
          items:
            type: string
    Response429:
      type: object
      properties:
        code:
          description: ''
          type: integer
        message:
          description: ''
          type: string
    IncomesItem:
      type: object
      properties:
        incomeId:
          type: integer
          description: Номер поставки
        number:
          type: string
          maxLength: 40
          description: Номер УПД
        date:
          type: string
          format: date
          description: Дата поступления. Если часовой пояс не указан, то берется Московское
            время UTC+3.
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе. Если часовой пояс не указан, то берется
            Московское время UTC+3.
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        techSize:
          type: string
          maxLength: 30
          description: Размер товара (пример S, M, L, XL, 42, 42-43)
        barcode:
          type: string
          maxLength: 30
          description: Бар-код
        quantity:
          type: integer
          description: Количество
        totalPrice:
          type: number
          description: Цена из УПД
        dateClose:
          type: string
          format: date
          description: Дата принятия (закрытия) в WB. Если часовой пояс не указан,
            то берется Московское время UTC+3.
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада
        nmId:
          type: integer
          description: Артикул WB
        status:
          type: string
          maxLength: 50
          enum:
            - Принято
          description: Текущий статус поставки
    StocksItem:
      type: object
      properties:
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе. Если часовой пояс не указан, то берется
            Московское время (UTC+3).
        warehouseName:
          type: string
          maxLength: 50
          description: Название склада
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        nmId:
          type: integer
          description: Артикул WB
        barcode:
          type: string
          maxLength: 30
          description: Баркод
        quantity:
          type: integer
          description: Количество, доступное для продажи (сколько можно добавить в
            корзину)
        inWayToClient:
          type: integer
          description: В пути к клиенту
        inWayFromClient:
          type: integer
          description: В пути от клиента
        quantityFull:
          type: integer
          description: Полное (непроданное) количество, которое числится за складом
            (= `quantity` + в пути)
        category:
          type: string
          maxLength: 50
          description: Категория
        subject:
          type: string
          maxLength: 50
          description: Предмет
        brand:
          type: string
          maxLength: 50
          description: Бренд
        techSize:
          type: string
          maxLength: 30
          description: Размер
        Price:
          type: number
          description: Цена
        Discount:
          type: number
          description: Скидка
        isSupply:
          type: boolean
          description: Договор поставки (внутренние технологические данные)
        isRealization:
          type: boolean
          description: Договор реализации (внутренние технологические данные)
        SCCode:
          type: string
          maxLength: 50
          description: Код контракта (внутренние технологические данные)
    OrdersItem:
      type: object
      properties:
        date:
          type: string
          format: date-time
          description: Дата и время заказа. Это поле соответствует параметру `dateFrom`
            в запросе, если параметр `flag`=1. Если часовой пояс не указан, то берется
            Московское время (UTC+3).
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе, если параметр `flag`=0 или не указан.
            Если часовой пояс не указан, то берется Московское время (UTC+3).
        warehouseName:
          type: string
          maxLength: 50
          description: Склад отгрузки
        countryName:
          type: string
          maxLength: 200
          description: Страна
        oblastOkrugName:
          type: string
          maxLength: 200
          description: Округ
        regionName:
          type: string
          maxLength: 200
          description: Регион
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        nmId:
          type: integer
          description: Артикул WB
        barcode:
          type: string
          maxLength: 30
          description: Баркод
        category:
          type: string
          maxLength: 50
          description: Категория
        subject:
          type: string
          maxLength: 50
          description: Предмет
        brand:
          type: string
          maxLength: 50
          description: Бренд
        techSize:
          type: string
          maxLength: 30
          description: Размер товара
        incomeID:
          type: integer
          description: Номер поставки
        isSupply:
          type: boolean
          description: Договор поставки
        isRealization:
          type: boolean
          description: Договор реализации
        totalPrice:
          type: number
          description: Цена без скидок
        discountPercent:
          type: integer
          description: Скидка продавца
        spp:
          type: number
          description: Скидка WB
        finishedPrice:
          type: number
          description: Фактическая цена с учетом всех скидок (к взиманию с покупателя)
        priceWithDisc:
          type: number
          description: Цена со скидкой продавца (= `totalPrice` * (1 - `discountPercent`/100))
        isCancel:
          type: boolean
          description: Отмена заказа. true - заказ отменен
        cancelDate:
          type: string
          format: date-time
          description: Дата и время отмены заказа. Если заказ не был отменен, то "0001-01-01T00:00:00".
            Если часовой пояс не указан, то берется Московское время UTC+3.
        orderType:
          type: string
          description: 'Тип заказа <ul> <li> `Клиентский` — заказ, поступивший от
            покупателя <li> `Возврат Брака` — возврат товара продавцу <li> `Принудительный
            возврат` — возврат товара продавцу <li> `Возврат обезлички` — возврат
            товара продавцу <li> `Возврат Неверного Вложения` — возврат товара продавцу
            <li> `Возврат Продавца` — возврат товара продавцу </ul>

            '
        sticker:
          type: string
          description: Идентификатор стикера
        gNumber:
          type: string
          maxLength: 50
          description: Номер заказа
        srid:
          type: string
          description: 'Уникальный идентификатор заказа.<br> Примечание для использующих
            API Маркетплейс: `srid` равен `rid` в ответах методов сборочных заданий.

            '
    SalesItem:
      type: object
      properties:
        date:
          type: string
          format: date-time
          description: Дата и время продажи. Это поле соответствует параметру `dateFrom`
            в запросе, если параметр `flag`=1. Если часовой пояс не указан, то берется
            Московское время (UTC+3).
        lastChangeDate:
          type: string
          format: date-time
          description: Дата и время обновления информации в сервисе. Это поле соответствует
            параметру `dateFrom` в запросе, если параметр `flag`=0 или не указан.
            Если часовой пояс не указан, то берется Московское время (UTC+3).
        warehouseName:
          type: string
          maxLength: 50
          description: Склад отгрузки
        countryName:
          type: string
          maxLength: 200
          description: Страна
        oblastOkrugName:
          type: string
          maxLength: 200
          description: Округ
        regionName:
          type: string
          maxLength: 200
          description: Регион
        supplierArticle:
          type: string
          maxLength: 75
          description: Артикул продавца
        nmId:
          type: integer
          description: Артикул WB
        barcode:
          type: string
          maxLength: 30
          description: Баркод
        category:
          type: string
          maxLength: 50
          description: Категория
        subject:
          type: string
          maxLength: 50
          description: Предмет
        brand:
          type: string
          maxLength: 50
          description: Бренд
        techSize:
          type: string
          maxLength: 30
          description: Размер товара
        incomeID:
          type: integer
          description: Номер поставки
        isSupply:
          type: boolean
          description: Договор поставки
        isRealization:
          type: boolean
          description: Договор реализации
        totalPrice:
          type: number
          description: Цена без скидок
        discountPercent:
          type: integer
          description: Скидка продавца
        spp:
          type: number
          description: Скидка WB
        forPay:
          type: number
          description: К перечислению продавцу
        finishedPrice:
          type: number
          description: Фактическая цена с учетом всех скидок (к взиманию с покупателя)
        priceWithDisc:
          type: number
          description: Цена со скидкой продавца, от которой считается сумма к перечислению
            продавцу `forPay` (= `totalPrice` * (1 - `discountPercent`/100))
        saleID:
          type: string
          maxLength: 15
          description: 'Уникальный идентификатор продажи/возврата <ul>  <li> `S**********`
            — продажа  <li> `R**********` — возврат (на склад WB)  </ul>

            '
        orderType:
          type: string
          description: 'Тип заказа <ul> <li> `Клиентский` — заказ, поступивший от
            покупателя <li> `Возврат Брака` — возврат товара продавцу <li> `Принудительный
            возврат` — возврат товара продавцу <li> `Возврат обезлички` — возврат
            товара продавцу <li> `Возврат Неверного Вложения` — возврат товара продавцу
            <li> `Возврат Продавца` — возврат товара продавцу </ul>

            '
        sticker:
          type: string
          description: Идентификатор стикера
        gNumber:
          type: string
          maxLength: 50
          description: Номер заказа
        srid:
          type: string
          description: 'Уникальный идентификатор заказа.<br> Примечание для использующих
            API Маркетплейс: `srid` равен `rid` в ответах методов сборочных заданий.

            '
    DetailReportItem:
      type: object
      properties:
        realizationreport_id:
          example: 1234567
          type: integer
          description: Номер отчёта
        date_from:
          example: '2022-10-17T00:00:00Z'
          type: string
          format: date-time
          description: Дата начала отчётного периода
        date_to:
          example: '2022-10-23T00:00:00Z'
          type: string
          format: date-time
          description: Дата конца отчётного периода
        create_dt:
          example: '2022-10-24T14:40:32'
          type: string
          format: date-time
          description: Дата формирования отчёта
        currency_name:
          example: руб
          type: string
          description: Валюта отчёта
        suppliercontract_code:
          example: null
          type: object
          description: Договор
        rrd_id:
          example: 1232610467
          type: integer
          description: Номер строки
        gi_id:
          example: 123456
          type: integer
          description: Номер поставки
        subject_name:
          example: Мини-печи
          type: string
          description: Предмет
        nm_id:
          example: 1234567
          type: integer
          description: Артикул WB
        brand_name:
          example: BlahBlah
          type: string
          description: Бренд
        sa_name:
          example: MAB123
          type: string
          description: Артикул продавца
        ts_name:
          example: '0'
          type: string
          description: Размер
        barcode:
          example: '1231312352310'
          type: string
          description: Баркод
        doc_type_name:
          example: Продажа
          type: string
          description: Тип документа
        quantity:
          type: integer
          example: 1
          description: Количество
        retail_price:
          example: 1249
          type: number
          description: Цена розничная
        retail_amount:
          example: 367
          type: number
          description: Сумма продаж (возвратов)
        sale_percent:
          example: 68
          type: integer
          description: Согласованная скидка
        commission_percent:
          example: 0.1324
          type: number
          description: Процент комиссии
        office_name:
          example: Коледино
          type: string
          description: Склад
        supplier_oper_name:
          example: Продажа
          type: string
          description: Обоснование для оплаты
        order_dt:
          example: '2022-10-13T00:00:00Z'
          type: string
          format: date-time
          description: Дата заказа. <br> Присылается с явным указанием часового пояса
        sale_dt:
          example: '2022-10-20T00:00:00Z'
          type: string
          format: date-time
          description: Дата продажи. <br> Присылается с явным указанием часового пояса
        rr_dt:
          example: '2022-10-20T00:00:00Z'
          type: string
          format: date-time
          description: Дата операции. <br> Присылается с явным указанием часового
            пояса
        shk_id:
          example: 1239159661
          type: integer
          description: Штрих-код
        retail_price_withdisc_rub:
          example: 399.68
          type: number
          description: Цена розничная с учетом согласованной скидки
        delivery_amount:
          example: 0
          type: integer
          description: Количество доставок
        return_amount:
          example: 0
          type: integer
          description: Количество возвратов
        delivery_rub:
          example: 0
          type: number
          description: Стоимость логистики
        gi_box_type_name:
          example: Монопалета
          type: string
          description: Тип коробов
        product_discount_for_report:
          example: 399.68
          type: number
          description: Согласованный продуктовый дисконт
        supplier_promo:
          example: 0
          type: number
          description: Промокод
        rid:
          example: 123722249253
          type: integer
          description: Уникальный идентификатор заказа
        ppvz_spp_prc:
          example: 0.1581
          type: number
          description: Скидка постоянного покупателя
        ppvz_kvw_prc_base:
          example: 0.15
          type: number
          description: Размер кВВ без НДС, % базовый
        ppvz_kvw_prc:
          example: -0.0081
          type: number
          description: Итоговый кВВ без НДС, %
        sup_rating_prc_up:
          type: number
          description: Размер снижения кВВ из-за рейтинга
        is_kgvp_v2:
          type: number
          description: Размер снижения кВВ из-за акции
        ppvz_sales_commission:
          example: -3.74
          type: number
          description: Вознаграждение с продаж до вычета услуг поверенного, без НДС
        ppvz_for_pay:
          example: 376.99
          type: number
          description: К перечислению продавцу за реализованный товар
        ppvz_reward:
          example: 0
          type: number
          description: Возмещение за выдачу и возврат товаров на ПВЗ
        acquiring_fee:
          example: 14.89
          type: number
          description: 'Возмещение издержек по эквайрингу. <br> Издержки WB за услуги
            эквайринга: вычитаются из вознаграждения WB и не влияют на доход продавца.

            '
        acquiring_bank:
          example: Тинькофф
          type: string
          description: Наименование банка-эквайера
        ppvz_vw:
          example: -3.74
          type: number
          description: Вознаграждение WB без НДС
        ppvz_vw_nds:
          example: -0.75
          type: number
          description: НДС с вознаграждения WB
        ppvz_office_id:
          example: 105383
          type: integer
          description: Номер офиса
        ppvz_office_name:
          example: Пункт самовывоза (ПВЗ)
          type: string
          description: Наименование офиса доставки
        ppvz_supplier_id:
          example: 186465
          type: integer
          description: Номер партнера
        ppvz_supplier_name:
          example: ИП Жасмин
          type: string
          description: Партнер
        ppvz_inn:
          example: '010101010101'
          type: string
          description: ИНН партнера
        declaration_number:
          example: ''
          type: string
          description: Номер таможенной декларации
        bonus_type_name:
          example: Штраф МП. Невыполненный заказ (отмена клиентом после недовоза)
          type: string
          description: 'Обоснование штрафов и доплат. <br> Поле будет в ответе при
            наличии значения

            '
        sticker_id:
          example: '1964038895'
          type: string
          description: Цифровое значение стикера, который клеится на товар в процессе
            сборки заказа по схеме "Маркетплейс"
        site_country:
          example: RU
          type: string
          description: Страна продажи
        penalty:
          example: 231.35
          type: number
          description: Штрафы
        additional_payment:
          example: 0
          type: number
          description: Доплаты
        rebill_logistic_cost:
          example: 1.349
          type: number
          description: 'Возмещение издержек по перевозке. Поле будет в ответе при
            наличии значения

            '
        rebill_logistic_org:
          example: ИП Иванов Иван Иванович(123456789012)
          type: string
          description: "Организатор перевозки. Поле будет в ответе при наличии значения.\
            \          \n"
        kiz:
          example: "0102900000376311210G2CIS?ehge)S\x1D91002A\x1D92F9Qof4FDo/31Icm14kmtuVYQzLypxm3HWkC1vQ/+pVVjm1dNAth1laFMoAGn7yEMWlTjxIe7lQnJqZ7TRZhlHQ=="
          type: string
          description: 'Код маркировки. <br> Поле будет в ответе при наличии значения

            '
        srid:
          example: 711ab8cb94e040f98b3804e5f331bf7a_r
          type: string
          description: 'Уникальный идентификатор заказа. Примечание для использующих
            API Marketplace: `srid` равен `rid` в ответах методов сборочных заданий.'
    ResponsePaidStorage:
      type: array
      items:
        type: object
        properties:
          date:
            type: string
            description: Дата
          logWarehouseCoef:
            type: integer
            description: Коэффициент логистики и хранения
          officeId:
            type: integer
            description: ID склада
          warehouse:
            type: string
            description: Название склада
          warehouseCoef:
            type: number
            description: Коэффициент склада
          giId:
            type: integer
            description: ID поставки
          chrtId:
            type: integer
            description: Числовой идентификатор размера для данного артикула WB
          size:
            type: string
            description: Размер (techSize в карточке товара)
          barcode:
            type: string
            description: Баркод
          subject:
            type: string
            description: Предмет
          brand:
            type: string
            description: Бренд
          vendorCode:
            type: string
            description: Артикул продавца
          nmId:
            type: integer
            description: Артикул WB
          volume:
            type: number
            description: Объём товара
          calcType:
            type: string
            description: Способ расчёта
          warehousePrice:
            type: number
            description: Сумма хранения
          barcodesCount:
            type: integer
            description: Количество товарных единиц (штук) на остатке, подлежащие
              тарифицированию за расчётные сутки.
          palletPlaceCode:
            type: integer
            description: Код палетоместа
          palletCount:
            type: number
            description: Количество палет
      example:
        - date: '2023-10-01'
          'logWarehouseCoef ': 0
          officeId: 507
          warehouse: Коледино
          warehouseCoef: 1.7
          giId: 123456
          chrt_id: 1234567
          size: '0'
          barcode: ''
          subject: Маски одноразовые
          brand: 1000 Каталог
          vendorCode: Артикул_продавца
          nmId: 1234567
          volume: 12
          calcType: 'короба: без габаритов'
          warehousePrice: 7.65
          barcodesCount: 1
          palletPlaceCode: 0
          palletCount: 0
    GetTasksRequest:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          description: ID заданий.
          minItems: 1
          maxItems: 50
          items:
            type: string
            format: uuid
    GetTasksResponse:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/GetTasksResponseData'
    GetTasksResponseData:
      type: object
      required:
        - tasks
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/GetTasksResponseTasks'
    GetTasksResponseTasks:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
          format: uuid
          description: ID задания
          x-go-name: ID
        status:
          type: string
          description: Статус задания
          enum:
            - new - новое
            - processing - обрабатывается
            - done - обработано успешно
            - purged - отчёт удалён
            - canceled - Отклонено
    CreateTaskRequest:
      discriminator:
        propertyName: type
        mapping:
          paid_storage: '#/components/schemas/CreateTaskRequestPaidStorage'
      oneOf:
        - $ref: '#/components/schemas/CreateTaskRequestPaidStorage'
    CreateTaskRequestPaidStorage:
      description: Схема тела запроса для получения отчёта "Платное хранение".
      type: object
      required:
        - params
        - type
      properties:
        type:
          type: string
          description: 'Тип отчёта:  <br><b>paid_storage</b> - Платное хранение

            '
          enum:
            - paid_storage
        params:
          type: object
          description: 'Параметры запроса необходимые для получения выбранного типа
            отчёта.

            '
          required:
            - dateFrom
            - dateTo
          properties:
            dateFrom:
              type: string
              format: date
              description: Дата начала запрашиваемого периода
            dateTo:
              type: string
              format: date
              description: Дата конца запрашиваемого периода
            diviser:
              type: integer
              description: Количество частей, на которое необходимо разделить запрошенный
                отчёт.
              example: 1
            remainder:
              type: integer
              description: Номер части отчёта, которую необходимо получить.
              example: 0
    CreateTaskResponse:
      type: object
      required:
        - data
      properties:
        data:
          $ref: '#/components/schemas/CreateTaskResponseData'
    CreateTaskResponseData:
      type: object
      required:
        - taskId
      properties:
        taskId:
          type: string
          format: uuid
          description: ID задания
    GetTasksResponseBytesError:
      type: object
      properties:
        data:
          type: object
          properties:
            tasks:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  last_proc_err:
                    type: string
                  status:
                    type: string
  parameters:
    flag:
      in: query
      name: flag
      schema:
        type: integer
        default: 0
      required: false
      description: 'Если параметр `flag=0` (или не указан в строке запроса), при вызове
        API возвращаются данные,  у которых значение поля `lastChangeDate` (дата время
        обновления информации в сервисе) больше или равно переданному  значению параметра
        `dateFrom`.  При этом количество возвращенных строк данных варьируется в интервале
        от 0 до примерно 100 000. <br> Если параметр `flag=1`, то будет выгружена
        информация обо всех заказах или продажах с датой,  равной переданному параметру
        `dateFrom` (в данном случае время в дате значения не имеет).  При этом количество
        возвращенных строк данных будет равно количеству всех заказов или продаж,  сделанных
        в указанную дату, переданную в параметре `dateFrom`.

        '
  examples:
    TokenMissing:
      description: Токен отсутствует
      value: 'proxy: unauthorized'
    TokenInvalid:
      description: Токен недействителен
      value: 'proxy: invalid token'
    TokenNotFound:
      description: Токен удален
      value: 'proxy: not found'
    TokenIsNotApplicable:
      description: Используемый токен не применим к данным методам.
      value: 'Error ae394f96-e258-432d-af13-a53a3d31f8b0: request rejected, unathorized:
        token scope not allowed for this API route'
    CantParseDateFrom:
      description: Ошибка в запросе
      value:
        errors:
          - can't parse dateFrom
    RequestTimeout:
      description: Тайм-аут запроса
      value:
        errors:
          - (api-new) request timeout
    RequestLimitStatistics:
      description: Превышено допустимое кол-во запросов в единицу времени
      value:
        code: 429
        message: error text
    GetTasksResponseData:
      value:
        data:
          tasks:
            - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
              status: new - новое
    GetTasksResponseBytesError:
      description: Размер запрошенного файла превышает допустимый. Разбейте отчёт
        на большее количество частей, либо запросите данные за меньший временной промежуток.
      value:
        data:
          tasks:
            - id: 1d9225ea-e61e-4a69-bb64-8b92a81ecdb6
              last_proc_err: report max bytes error
              status: error
    ErrorDifferenceBetweenDateFromDateTo:
      description: Разница значений между dateFrom и dateTo должна быть меньше или
        равна 8 дням.
      value:
        errors:
          - Difference between dateFrom and dateTo should be less or equal 8 days
    ErrorResponseTasksCreate:
      value:
        errors:
          - string
paths:
  /api/v1/supplier/incomes:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      security:
        - HeaderApiKey: [ ]
      summary: Поставки
      description: Поставки.
      tags:
        - Статистика
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Дата и время последнего изменения по поставке. <br> Дата в формате
          RFC3339. Можно передать дату или дату со временем.  Время можно указывать
          с точностью до секунд или миллисекунд. <br> Время передаётся в часовом поясе
          Мск (UTC+3). <br>Примеры: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59`
          <li> `2019-06-20T00:00:00.12345` <li> `2017-03-25T00:00:00` </ul>

          '
      responses:
        200:
          description: Список поставок
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IncomesItem'
              example:
                - incomeId: 12345
                  number: ''
                  date: '2022-05-08T00:00:54'
                  lastChangeDate: '2022-05-08T00:44:15.5'
                  supplierArticle: ABCDEF
                  techSize: '0'
                  barcode: '2000328074123'
                  quantity: 3
                  totalPrice: 0
                  dateClose: '2022-05-08T00:00:00'
                  warehouseName: Подольск
                  nmId: 1234567
                  status: Принято
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/stocks:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: [ ]
      summary: Склад
      description: 'Остатки товаров на складах WB. Данные обновляются раз в 30 минут.
        <br> Сервис статистики не хранит историю остатков товаров, поэтому получить
        данные о них можно только в режиме "на текущий момент".

        '
      tags:
        - Статистика
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Дата и время последнего изменения по товару. <br> Для получения
          полного остатка следует указывать максимально раннее значение. <br> Например,
          `2019-06-20` <br> Дата в формате RFC3339. Можно передать дату или дату со
          временем.  Время можно указывать с точностью до секунд или миллисекунд.
          <br> Время передаётся в часовом поясе Мск (UTC+3). <br>Примеры: <ul> <li>
          `2019-06-20` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345`
          <li> `2017-03-25T00:00:00` </ul>

          '
      responses:
        200:
          description: Список товаров на складе
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StocksItem'
              example:
                - lastChangeDate: '2023-07-05T11:13:35'
                  warehouseName: Краснодар
                  supplierArticle: '443284'
                  nmId: 1439871458
                  barcode: '2037401340280'
                  quantity: 33
                  inWayToClient: 1
                  inWayFromClient: 0
                  quantityFull: 34
                  category: Посуда и инвентарь
                  subject: Формы для запекания
                  brand: X
                  techSize: '0'
                  Price: 185
                  Discount: 0
                  isSupply: true
                  isRealization: false
                  SCCode: Tech
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/orders:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: [ ]
      summary: Заказы
      description: 'Заказы. <br> Гарантируется хранение данных не более 90 дней от
        даты заказа. <br> Данные обновляются раз в 30 минут. <br> Для идентификации
        заказа следует использовать поле `srid`. <br> 1 строка = 1 заказ = 1 единица
        товара. <br>

        '
      tags:
        - Статистика
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Дата и время последнего изменения по заказу. <br> Дата в формате
          RFC3339. Можно передать дату или дату со временем.  Время можно указывать
          с точностью до секунд или миллисекунд. <br> Время передаётся в часовом поясе
          Мск (UTC+3). <br>Примеры: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59`
          <li> `2019-06-20T00:00:00.12345` <li> `2017-03-25T00:00:00` </ul>

          '
        - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Список заказов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrdersItem'
              example:
                - date: '2022-03-04T18:08:31'
                  lastChangeDate: '2022-03-06T10:11:07'
                  warehouseName: Подольск
                  countryName: Россия
                  oblastOkrugName: Центральный федеральный округ
                  regionName: Московская
                  supplierArticle: '12345'
                  nmId: 1234567
                  barcode: '123453559000'
                  category: Бытовая техника
                  subject: Мультистайлеры
                  brand: Тест
                  techSize: '0'
                  incomeID: 56735459
                  isSupply: false
                  isRealization: true
                  totalPrice: 1887
                  discountPercent: 18
                  spp: 26
                  finishedPrice: 1145
                  priceWithDisc: 1547
                  isCancel: true
                  cancelDate: '2022-03-09T00:00:00'
                  orderType: Клиентский
                  sticker: '926912515'
                  gNumber: '34343462218572569531'
                  srid: 11.rf9ef11fce1684117b0nhj96222982382.3.0
        400:
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseErrorStatistics'
              examples:
                CantParseDateFrom:
                  $ref: '#/components/examples/CantParseDateFrom'
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/sales:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: [ ]
      summary: Продажи
      description: 'Продажи и возвраты. <br> Гарантируется хранение данных не более
        90 дней от даты продажи. <br> Данные обновляются раз в 30 минут. <br> Для
        идентификации заказа следует использовать поле `srid`. <br> 1 строка = 1 продажа/возврат
        = 1 единица товара.  <br>

        '
      tags:
        - Статистика
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Дата и время последнего изменения по продаже/возврату. <br>
          Дата в формате RFC3339. Можно передать дату или дату со временем.  Время
          можно указывать с точностью до секунд или миллисекунд. <br> Время передаётся
          в часовом поясе Мск (UTC+3). <br>Примеры: <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59`
          <li> `2019-06-20T00:00:00.12345` <li> `2017-03-25T00:00:00` </ul>

          '
        - $ref: '#/components/parameters/flag'
      responses:
        200:
          description: Список продаж
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SalesItem'
              example:
                - date: '2022-03-04T18:08:31'
                  lastChangeDate: '2022-03-06T10:11:07'
                  warehouseName: Подольск
                  countryName: Россия
                  oblastOkrugName: Центральный федеральный округ
                  regionName: Московская
                  supplierArticle: '12345'
                  nmId: 1234567
                  barcode: '123453559000'
                  category: Бытовая техника
                  subject: Мультистайлеры
                  brand: Тест
                  techSize: '0'
                  incomeID: 56735459
                  isSupply: false
                  isRealization: true
                  totalPrice: 1887
                  discountPercent: 18
                  spp: 26
                  forPay: 1284.01
                  finishedPrice: 1145
                  priceWithDisc: 1547
                  saleID: S9993700024
                  orderType: Клиентский
                  sticker: '926912515'
                  gNumber: '34343462218572569531'
                  srid: 11.rf9ef11fce1684117b0nhj96222982382.3.0
        400:
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responseErrorStatistics'
              examples:
                CantParseDateFrom:
                  $ref: '#/components/examples/CantParseDateFrom'
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/supplier/reportDetailByPeriod:
    servers:
      - url: https://statistics-api.wildberries.ru/
    get:
      security:
        - HeaderApiKey: [ ]
      summary: Отчет о продажах по реализации
      description: "Детализация к отчету реализации.  <br> В отчете доступны данные\
        \ за последние 3 месяца. <br> В случае отсутствия данных за указанный период\
        \ метод вернет `null`. <br> Технический перерыв в работе метода: каждый понедельник\
        \ с 3:00 до 16:00. <br> <a href=\"../../excel_save/ru/index.html\">Инструкция:\
        \ Сохранение статистики в Excel</a> \n"
      tags:
        - Статистика
      parameters:
        - name: dateFrom
          in: query
          schema:
            type: string
            format: RFC3339
          required: true
          description: 'Начальная дата отчета.<br> Дата в формате RFC3339. Можно передать
          дату или дату со временем.  Время можно указывать с точностью до секунд
          или миллисекунд. <br> Время передаётся в часовом поясе Мск (UTC+3). <br>Примеры:
          <ul> <li> `2019-06-20` <li> `2019-06-20T23:59:59` <li> `2019-06-20T00:00:00.12345`
          <li> `2017-03-25T00:00:00` </ul>

          '
        - in: query
          name: limit
          schema:
            type: integer
            default: 100000
          required: false
          description: Максимальное количество строк отчета, возвращаемых методом. Не
            может быть более 100000.
        - in: query
          name: dateTo
          schema:
            type: string
            format: date
          required: true
          description: Конечная дата отчета
        - in: query
          name: rrdid
          schema:
            type: integer
          required: false
          description: "Уникальный идентификатор строки отчета. Необходим для получения\
          \ отчета частями. \n<br>\nЗагрузку отчета нужно начинать с `rrdid = 0` и\
          \ при последующих вызовах API передавать в запросе значение `rrd_id` из\
          \ последней строки, полученной в результате предыдущего вызова. \n<br>\n\
          Таким образом для загрузки одного отчета может понадобиться вызывать API\
          \ до тех пор, пока количество возвращаемых строк не станет равным нулю.\n"
      responses:
        200:
          description: Список реализованных позиций
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DetailReportItem'
        401:
          description: Не авторизован
          content:
            application/json:
              schema:
                type: string
              examples:
                TokenMissing:
                  $ref: '#/components/examples/TokenMissing'
                TokenInvalid:
                  $ref: '#/components/examples/TokenInvalid'
                TokenIsNotApplicable:
                  $ref: '#/components/examples/TokenIsNotApplicable'
                TokenNotFound:
                  $ref: '#/components/examples/TokenNotFound'
        429:
          description: ''
          content:
            application/json:
              schema:
                oneOf:
                  - type: string
                  - $ref: '#/components/schemas/Response429'
              examples:
                TechnicalBreak:
                  value: 'Технический перерыв в работе метода: каждый понедельник
                    с 3:00 до 16:00.'
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /--:
    servers:
      - url: https://--.--
    get:
      tags:
        - Отчёты
      summary: Платное хранение
      description: 'Расчёт стоимости хранения товаров на складах. <br> `Важно!` Это
        не метод, а только описание полей отчёта. <br> Процесс получения отчётов описан
        в разделе <b>Отложенная генерация</b>.

        '
      responses:
        200:
          description: Платное хранение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponsePaidStorage'
  /api/v1/delayed-gen/tasks/create:
    servers:
      - url: https://statistics-api.wildberries.ru
    post:
      security:
        - HeaderApiKey: [ ]
      tags:
        - Получение отчётов
      summary: Создание задания на генерацию отчёта
      description: 'Метод позволяет создавать задание на генерацию необходимого отчета.
        <br> <br> <b>Детали получения отчёта о платном хранении:</b>   <br> Максимальный
        диапазон дат - 8 дней. <br> За один запрос получить отчёт можно только в том
        случае, если размер его не превышает 50 мб. Если размер отчёта больше, то
        воспользуйтесь параметрами <code>diviser</code> и <code>remainder</code>,
        чтобы получить отчёт по частям.<br> Понять, что размер отчёта превышает 50
        мб, можно проверив статус задания. В ответе будет содержжаться строка "report
        max bytes error"

        '
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
        required: true
      responses:
        201:
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTaskResponse'
        400:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ErrorResponseTasksCreate:
                  $ref: '#/components/examples/ErrorResponseTasksCreate'
                ErrorDifferenceBetweenDateFromDateTo:
                  $ref: '#/components/examples/ErrorDifferenceBetweenDateFromDateTo'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
  /api/v1/delayed-gen/tasks:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      security:
        - HeaderApiKey: [ ]
      tags:
        - Получение отчётов
      summary: Получить статус задания
      description: Позволяет получать статус задания на генерацию отчета.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTasksRequest'
        required: true
      responses:
        200:
          description: Информация по задаче генерации
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/GetTasksResponse'
                  - $ref: '#/components/schemas/GetTasksResponseBytesError'
              examples:
                GetTasksResponseData:
                  $ref: '#/components/examples/GetTasksResponseData'
                GetTasksResponseBytesError:
                  $ref: '#/components/examples/GetTasksResponseBytesError'
        400:
          $ref: '#/components/responses/400BadRequest'
        404:
          $ref: '#/components/responses/404EntityNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
        500:
          $ref: '#/components/responses/500InternalError'
  /api/v1/delayed-gen/tasks/download:
    servers:
      - url: https://statistics-api.wildberries.ru
    get:
      security:
        - HeaderApiKey: [ ]
      tags:
        - Получение отчётов
      summary: Получить отчёт по ID задания
      description: Метод позволяет получать сгенерированный отчёт по ID задания.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DownloadRequest'
        required: true
      responses:
        200:
          description: Запрашиваемые данные. <br> Описание см. в разделе документации
            Отчёты.
        400:
          $ref: '#/components/responses/400BadRequest'
        404:
          $ref: '#/components/responses/404EntityNotFound'
        429:
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response429'
              examples:
                RequestLimitStatistics:
                  $ref: '#/components/examples/RequestLimitStatistics'
        500:
          $ref: '#/components/responses/500InternalError'